# Generated by Django 4.2.19 on 2025-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
    ]
